[package]
name = "never_gonna_suck"
version = "0.1.0"
authors = ["UnTea <weqqu2014@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
byteorder = "1.4.3"